---
name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    steps:
    - name: Checkout project
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Build project
      run: |
          git config --global --add safe.directory `pwd` && \
          git submodule update --remote && make -j2

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ovlSysmodules.ovl
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.release_token }}
        file: ./ovlSysmodules.ovl
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        make_latest: true 
